version: '2'
services:
  phpfpm:
    image: rlewkowicz/php-fpm:latest
    volumes:
    - "./distribution-files/etc:/usr/local/etc"
    - "./distribution-files/mwcore/mediawiki:/var/www/mediawiki"
    - "/etc/passwd:/etc/passwd:ro"
    - "/etc/shadow:/etc/shadow:ro"
    - "/etc/group:/etc/group:ro"
  nginx:
    image: nginx:1.10
    ports:
    - "80:80"
    - "443:443"
    - "8000:8000"
    volumes:
    - "./distribution-files/nginx:/etc/nginx"
    - "./distribution-files/mwcore/mediawiki:/var/www/mediawiki"
    - "/etc/passwd:/etc/passwd:ro"
    - "/etc/shadow:/etc/shadow:ro"
    - "/etc/group:/etc/group:ro"
    depends_on:
    - phpfpm
    - parsoid
  mysql:
    image: mariadb:10.0
    volumes:
    - "./distribution-files/mysql:/var/lib/mysql"
    environment:
    - MYSQL_ROOT_PASSWORD=@6gRzU2k8%
    - MYSQL_USER=root@myadmin
    - MYSQL_PASSWORD=@6gRzU2k8%
    depends_on:
    - nginx
  parsoid:
    image: rlewkowicz/parsoid:latest
    volumes:
    - "./distribution-files/parsoid/config.yaml:/usr/local/lib/node_modules/parsoid/config.yaml"
    hostname: parsoid
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
    environment:
    - PMA_HOST=mysql
    depends_on:
    - mysql
  cass:
    image: cassandra:3
    volumes:
    - "./distribution-files/cassandra_data:/var/lib/cassandra"
    - "./distribution-files/cassandra_conf/cassandra.yaml:/etc/cassandra/cassandra.yaml"
  restbase:
    image: rlewkowicz/restbase:latest
    volumes:
    - "./distribution-files/cassandra_data:/var/lib/cassandra"
    - "./distribution-files/restbase/config.yaml:/usr/local/lib/node_modules/restbase/config.yaml"
